[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipdb>=0.13.13",
    "ipython>=9.6.0",
    "numpy>=2.3.3",
    "pillow>=11.3.0",
    "qrcode>=8.2",
    "requests>=2.32.5",
]
