
services:
  rain_radar_app:
    build: .
    image: pico_dev:latest
    volumes:
      - ./rain_radar_app:/home/appuser/pico/rain_radar_app         # Mount local folder
      - ../../pimoroni-pico:/home/appuser/pico/pimoroni-pico
    working_dir: /home/appuser/pico/rain_radar_app      # Set working directory
    tty: true             # Keep terminal open
    stdin_open: true      # Allow interactive input